apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: openyurt
data:
  nginx.conf: |
    worker_processes auto;

    # 必须的 events 配置
    events {
        worker_connections 1024;
    }

    stream {
        upstream backend_tcp_6443 {
            server 10.185.0.4:6443;
        }
        server {
            listen 6443;
            proxy_pass backend_tcp_6443;
        }

        upstream backend_tcp_18443 {
            server 10.185.0.4:18443;
        }
        server {
            listen 18443;
            proxy_pass backend_tcp_18443;
        }

        upstream backend_tcp_38443 {
            server 10.185.0.4:38443;
        }
        server {
            listen 38443;
            proxy_pass backend_tcp_38443;
        }

        upstream backend_udp_4500 {
            server 10.185.0.4:4500;
        }
        server {
            listen 4500 udp;
            proxy_pass backend_udp_4500;
        }

        upstream backend_udp_123 {
            server 10.185.0.4:123;
        }
        server {
            listen 123 udp;
            proxy_pass backend_udp_123;
        }
    }
