apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox
  namespace: test
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - /bin/sh
        - -c
        - sleep 3000